### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by andreasabel** [klapaucius/vector-hashtables#13]
Would be great to have `vector-hashtables` added to stackage nightly.

Update: Blocked by
- [x] #11

**Comment by andreasabel** [comment]
This is getting more pressing now:
- https://github.com/commercialhaskell/stackage/issues/6871

Looks like I have to do this myself.

**Comment by ulysses4ever** [comment]
I can do stackage is Andreas doesn't beat me to it.

**Comment by ulysses4ever** [comment]
I guess I'm late for the party: https://github.com/commercialhaskell/stackage/pull/6872 Thanks, Andreas!

**Comment by andreasabel** [comment]
It would be best if the actual maintainer would also be stackage maintainer.
So, Andrey @swamp-agr , if you want to open a PR to stackage instead, I am happy to close mine:
- https://github.com/commercialhaskell/stackage/pull/6872

**Comment by swamp-agr** [comment]
@andreasabel thanks for pointing it out. Please expect PR either from me or from @ulysses4ever soon.

**Comment by ulysses4ever** [comment]
Done: https://github.com/commercialhaskell/stackage/pull/6873

**Comment by ulysses4ever** [comment]
Since https://github.com/commercialhaskell/stackage/pull/6873 is merged, this one can be closed I guess?
