### ISSUE TITLE
Strict-in-value variations of alter / upsert

### ISSUE THREAD

**Issue by Bodigrim** [klapaucius/vector-hashtables#23]
As noticed by @sgraf812 at https://discourse.haskell.org/t/one-billion-row-challenge-in-hs/8946/95, `alter` / `upsert` do not force the value they insert into a hashtable, which potentially leads to accumulation of thunks. There are two possible solutions:

* Implement, say, `upsert'` / `alter'` which are strict in values, and leave the semantics of existing `alter` / `upsert` unchanged.

* Just make the underlying `insertWithIndex` strict in value. This would change existing `alter` / `upsert` to be stricter, but I guess in the majority of scenarios it's a welcome change?..

@swamp-agr @ulysses4ever what do you think?

**Comment by ulysses4ever** [comment]
I'm in support. I think it'd prefer to add "primed" versions to not steal the existing behavior completely. But I don't have a strong opinion.

**Comment by Bodigrim** [comment]
Yeah, I guess it's possible to use hashtables with intentionally lazy values for recursive computations / caching...

**Comment by Bodigrim** [comment]
OTOH maybe it's just a matter of documentation. Hashtables are already polymorphic by vector flavour, so one can use a [strict vector](https://hackage.haskell.org/package/strict-containers-0.2/docs/Data-Strict-Vector.html) from [`strict-containers`](https://hackage.haskell.org/package/strict-containers) to solve the root problem. See also https://github.com/haskell/vector/issues/483

**Comment by ulysses4ever** [comment]
@klapaucius privately expressed his preference to strict-by-default alter, so that's the plan now it seems. And if any user wants the lazy behavior, we can always add alterLazy (same for upsert).

Although the solution with strict-containers is more flexible, the point of this package, I think, is to optimize UX for the common case, which is better served by strict values.

**Comment by Bodigrim** [comment]
> And if any user wants the lazy behavior, we can always add alterLazy (same for upsert).

You'd also have to change and provide lazy versions of `alterM`, `unionWith`, `unionWithKey`, `differenceWith`, `intersectionWith`, `intersectionWithKey`, and potentially even more to cover `Data.Vector.Hashtables.Internal` as well. 

On contrary to my initial opinion on the issue, now I think that it's not worth it. Instead of plugging every hole in every part of the API, which is tedious and error prone, it is easier to make invalid laziness unrepresentable. One should not have to review implementation each time they have doubts about thunks, it should be enough to check types. Strict vectors are likely to be upstreamed from `strict-containers` to `vector` proper soon (https://github.com/haskell/vector/tree/strict-vector). 

Anyway, I'm happy to leave this for you folks to decide. If I may, I'd still suggest merging #27, because it documents the current best practice. If some future developments make this documentation obsolete, it can be removed.

**Comment by ulysses4ever** [comment]
It's a very convincing case above.
